### PR TITLE
Introduce element aware encoders

### LINKED ISSUE #25: anyType encoder with xsi type
### Support Question

I tried to follow the examples and set up custom `anyType` encoder that could inject 'non-string' XML.

```php
$registry->addSimpleTypeConverter(
    namespace: Xmlns::xsd()->value(),
    name: 'anyType',
    encoder: new AnyTypeEncoder(new MyObjectTypeEncoder()),
);
```

`AnyTypeEncoder` is pretty much a proxy into `MyObjectTypeEncoder`:

```php
/**
 * @template T of GetMyObjectRequestType|GetMyObjectResponseType
 * @implements XmlEncoder<T, string>
 */
final class MyObjectTypeEncoder implements XmlEncoder, XsiTypeCalculator
{
    private SerializerInterface $serializer;

    public function __construct()
    {
        $this->serializer = MyObjectSerializerFactory::createSerializer();
    }

    /**
     * @return Iso<T, string>
     */
    public function iso(Context $context): Iso
    {
        return new Iso(
            fn(mixed $data): string => $this->to($context, $data),
            fn(string $data): mixed => match ($context->type->getName()) {
                GetMyObjectRequestType::class => $this->serializer->deserialize($data, GetMyObjectRequestType::class, 'xml'),
                GetMyObjectResponseType::class => $this->serializer->deserialize($data, GetMyObjectResponseType::class, 'xml'),
                default => throw RestrictionException::unsupportedValueType($context->type, $data),
            },
        );
    }

    /**
     * @param T $data
     * @return non-empty-string
     */
    private function to(Context $context, mixed $data): string
    {
        $wrapped = $this->serializer->serialize(
            data: $data,
            format: 'xml',
        );

        return str_replace(['<result>', '</result>'], '', trim_xml_header($wrapped));
    }

    public function resolveXsiTypeForValue(Context $context, mixed $value): string
    {
        return match (true) {
            $value instanceof GetMyObjectRequestType => 'getMyObjectRequestType',
            $value instanceof GetMyObjectResponseType => 'getMyObjectResponseType',
            default => ElementValueBuilder::resolveXsiTypeForValue($context, $value),
        };
    }

    public function shouldIncludeXsiTargetNamespace(Context $context): bool
    {
        return true;
    }
}
```

My first problem is that the resulting output is escaped and looks like this:

```
<data xsi:type="getMyObjectRequestType" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  &lt;ns-001db19f:field1 xmlns:ns-001db19f=&quot;http://example.com/ns/my/object&quot;&gt;value1&lt;/ns-001db19f:field1&gt;
  &lt;ns-001db19f:field2 xmlns:ns-001db19f=&quot;http://example.com/ns/my/object&quot;&gt;value2&lt;/ns-001db19f:field2&gt;
  &lt;ns-001db19f:field3 xmlns:ns-001db19f=&quot;http://example.com/ns/my/object&quot;&gt;value3&lt;/ns-001db19f:field3&gt;
</data>
```

whereas I want it to be a proper XML:

```
<data xsi:type="getUserDataRequestType" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ns-001db19f:field1 xmlns:ns-001db19f="http://example.com/ns/my/object">value1</ns-001db19f:field1>
  <ns-001db19f:field2 xmlns:ns-001db19f="http://example.com/ns/my/object">value2</ns-001db19f:field2>
  <ns-001db19f:field3 xmlns:ns-001db19f="http://example.com/ns/my/object">value3</ns-001db19f:field3>
</data>
```

My second problem is that I'm using a JMS Serializer for an XSD schema that only defines types, i.e the there are no elements, so my serializer have not types with `xml_root_name`. Because of that serialized output will wrap the XML with `<result>` root.

What would be my best course of action to fake a root object that could be recognized as `anyType` mixed element?

On ext-soap-engine, I used to hack the input by wrapping it like `$data = new \SoapVar(trim_xml_header($xml), XSD_ANYXML);`.

While writing this, I realized that the xsd type was supposed to be `anyxml`. But from what I've seen in the wild, `anyType` should also support non-escaped output when xsi:type is explicitly not a string.

### PR DESCRIPTION
**Pull request by veewee**
|      Q       |   A
|------------- | -----------
| Type         | feature
| BC Break     | no
| Fixed issues | #25

#### Summary

Fixes #25 

```php
/**
 * Most of the time, you don't need access to the wrapping XML element from within a simple type encoder.
 * Sometimes, when using anyXml or anyType, you might want to have full control over the wrapping element.
 * This allows you to use 3rd party tools to build the full XML structure from within a simple type encoder.
 *
 * Do note that:
 * - You'll need to check if the current provided type is an attribute or not.
 * - If you want to add xsi:type information, you need to add / parse it manually.
 * - The result will be used as a raw XML input, meaning it should be valid XML (without the header declearations).
 */
EncoderRegistry::default()
    ->addSimpleTypeConverter(
        'http://www.w3.org/2001/XMLSchema',
        'anyXml',
        new class implements XmlEncoder, ElementAware {
            public function iso(Context $context): Iso
            {
                if ($context->type->getMeta()->isAttribute()->unwrapOr(false)) {
                    return (new ScalarTypeEncoder())->iso($context);
                }

                $targetElementName = $context->type->getXmlTargetNodeName();
                return new Iso(
                    to: static fn (array $data): string => document_encode([$targetElementName => $data])
                        ->manipulate(static fn (\DOMDocument $document) => $document->documentElement->setAttributeNS(
                            VeeWee\Xml\Xmlns\Xmlns::xsi()->value(),
                            'xsi:type',
                            'custom:type'
                        ))
                        ->stringifyDocumentElement(),
                    from: static fn (string $xml): array => xml_decode($xml)[$targetElementName],
                );
            }
        }
    );

```

/cc @rauanmayemir : can you check if this allows you to solve the issues you are facing?

### CODE REVIEW

**Comment by rauanmayemir** [comment]
`request` part worked as expected, gotta get used to this new way. Trying the `response` part now.

**Comment by rauanmayemir** [comment]
@veewee This is a dream come true 🥹🥹🥹 

`data` is perfectly decoded from XSD-backed types.

image


Kindly request for guidance for a situation where my `data` is of `anyType` and the incoming XML string looks like:

```
<data><ns123:response>...</ns123:response></data>
```

I always get confused with how to use Xml locators and manipulators with proper chaining, so the code looks a bit ugly:
```
      $value = Document::fromXmlNode(
          Document::fromXmlNode($data->element())
              ->locate(Locator\elements_with_tagname('response'))
              ->item(0),
      )
          ->toXmlString();

      return $this->serializer->deserialize(
          data: $value,
          type: Response::class,
          format: 'xml'
      );
```

**Comment by rauanmayemir** [comment]
Thank you, that looks much better!
Should this be merged and tagged?

**Comment by veewee** [comment]
Tagged ;)

**Pull request merged**
